# Standard Prometheus configuration converted from Kubernetes CRD
# Original file: /home/sprime01/homelab/homelab-observability/configs/prometheus/prometheus-config.yaml
# Note: This is a simplified version for validation purposes only

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Rule files to load
rule_files:
  - "/etc/prometheus/rules/*.yaml"

# Alerting configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - "alertmanager:9093"

# Scrape configurations
scrape_configs:
  # Self monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Example node exporter targets
  - job_name: 'node'
    static_configs:
      - targets:
        - 'node-exporter:9100'
        - 'localhost:9100'

  # Example application targets
  - job_name: 'applications'
    static_configs:
      - targets:
        - 'app-server:8080'
        - 'database:9187'

  # Kubernetes service discovery
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        action: replace
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_pod_name]
        action: replace
        target_label: kubernetes_pod_name

  - job_name: 'kubernetes-services'
    kubernetes_sd_configs:
      - role: service
    relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: kubernetes_name
